version: '3'

# networks:
#   app-tier:
#     driver: bridge

services:
  db:
    image: bitnami/postgresql
    ports: 
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=igma
      - POSTGRESQL_PASSWORD=igma
      - POSTGRESQL_DATABASE=igma
     # image: postgres
    # ports: 
    #   - 5432:5432
    # environment:
    #   - POSTGRES_USER=igma
    #   - POSTGRES_DB=igma
    #   - POSTGRES_PASSWORD=igma
    # networks:
    #   - app-tier
    
  # igma_backend:
  #   build: 
  #     context: .
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - db
  #   # networks:
  #   #   - app-tier
